# Generated by Django 5.2.6 on 2025-09-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='remaining_allowance',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
